///////////////////////////////////////////////////////////
// following data is only for an example
// any reference to living persons are purely coincidental
///////////////////////////////////////////////////////////

module.exports = {
  patients: [
    {
      familyName: 'Иванов',
      firstName: 'Степан',
      fathersName: 'Аркадьевич',
      dateOfBirth: new Date('1982-06-12'),
      officialSex: 'male',
      biologicalSex: '',
      address: '424000, г. Йошкар-Ола, ул. Красноармейская, д. 103. кв. 55',
      phoneNumber: '+7-899-000-00-00',
      lastUpdate: new Date(),
      updates: [],
      notes: [
        {
          date: new Date('2019-02-13'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит голова',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со стороны ЧН - б/о. СПР D=S, оживлены',
          },
        },
        {
          date: new Date('2019-01-15'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит спина.',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со ст. ЧН - б/о. СПР D=S, оживлены',
          },
        },
      ],
    },
    {
      familyName: 'Иванов',
      firstName: 'Антон',
      fathersName: 'Николаевич',
      dateOfBirth: new Date('1990-07-24'),
      officialSex: 'male',
      biologicalSex: '',
      address: '424000, г. Йошкар-Ола, ул. Красноармейская, д. 103. кв. 55',
      phoneNumber: '+7-899-000-00-00',
      lastUpdate: new Date(),
      updates: [],
      notes: [
        {
          date: new Date('2019-02-13'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит голова',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со стороны ЧН - б/о. СПР D=S, оживлены',
          },
        },
        {
          date: new Date('2019-01-15'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит спина.',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со ст. ЧН - б/о. СПР D=S, оживлены',
          },
        },
      ],
    },
    {
      familyName: 'Иванов',
      firstName: 'Кирилл',
      fathersName: 'Филиппович',
      dateOfBirth: new Date('1987-12-30'),
      officialSex: 'male',
      biologicalSex: '',
      address: '424000, г. Йошкар-Ола, ул. Красноармейская, д. 103. кв. 55',
      phoneNumber: '+7-899-000-00-00',
      lastUpdate: new Date(),
      updates: [],
      notes: [
        {
          date: new Date('2019-02-13'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит голова',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со стороны ЧН - б/о. СПР D=S, оживлены',
          },
        },
        {
          date: new Date('2019-01-15'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит спина.',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со ст. ЧН - б/о. СПР D=S, оживлены',
          },
        },
      ],
    },
    {
      familyName: 'Петров',
      firstName: 'Юрий',
      fathersName: 'Николаевич',
      dateOfBirth: new Date('1943-01-29'),
      officialSex: 'male',
      biologicalSex: '',
      address: '424000, г. Йошкар-Ола, ул. Красноармейская, д. 103. кв. 55',
      phoneNumber: '+7-899-000-00-00',
      lastUpdate: new Date(),
      updates: [],
      notes: [
        {
          date: new Date('2019-02-13'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит голова',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со стороны ЧН - б/о. СПР D=S, оживлены',
          },
        },
        {
          date: new Date('2019-01-15'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит спина.',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со ст. ЧН - б/о. СПР D=S, оживлены',
          },
        },
      ],
    },
    {
      familyName: 'Уругваева',
      firstName: 'Анна',
      fathersName: 'Михайловна',
      dateOfBirth: new Date('1990-03-19'),
      officialSex: 'female',
      biologicalSex: '',
      address: '424000, г. Йошкар-Ола, ул. Красноармейская, д. 103. кв. 55',
      phoneNumber: '+7-899-000-00-00',
      lastUpdate: new Date(),
      updates: [],
      notes: [
        {
          date: new Date('2019-02-13'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит голова',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со стороны ЧН - б/о. СПР D=S, оживлены',
          },
        },
        {
          date: new Date('2019-01-15'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит спина.',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со ст. ЧН - б/о. СПР D=S, оживлены',
          },
        },
      ],
    },
    {
      familyName: 'Куюкина',
      firstName: 'София',
      fathersName: 'Григорьевна',
      dateOfBirth: new Date('2013-06-12'),
      officialSex: 'female',
      biologicalSex: '',
      address: '424000, г. Йошкар-Ола, ул. Красноармейская, д. 103. кв. 55',
      phoneNumber: '+7-899-000-00-00',
      lastUpdate: new Date(),
      updates: [],
      notes: [
        {
          date: new Date('2019-02-13'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит голова',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со стороны ЧН - б/о. СПР D=S, оживлены',
          },
        },
        {
          date: new Date('2019-01-15'),
          dateAdded: new Date(),
          doctor: 'Smolin',
          medcenter: 'Luch',
          cardNumber: '75643',
          noteType: 'ambneur',
          data: {
            complaints: 'Болит спина.',
            objective: 'BP 120/80 mmHg, HR 72 min, живот мягкий, б/б.',
            neurStatus: 'В сознании. Со ст. ЧН - б/о. СПР D=S, оживлены',
          },
        },
      ],
    },
  ],
};
